---
- name: Debian Config - Debian Baseline & Post-Install
  hosts: default
  gather_facts: true
  become: true

  tasks:
    - ansible.builtin.include_tasks: tasks/baseline.yml
    - ansible.builtin.include_tasks: tasks/postinstall.yml
